prometheus:
  agentMode: true
  prometheusSpec:
    replicas: 2
    replicaExternalLabelName: "agent_replica"
    externalLabels:
      cluster: "workload-cluster"
    remoteWrite:
    - name: "workload-cluster-remote-write"
      # TODO fix this and use https instead:
      url: "http://<ip-of-node>:30291/api/v1/receive"

## See https://github.com/dNationCloud/kubernetes-monitoring-stack/blob/main/chart/values.yaml#L264
prometheus-node-exporter:
  extraArgs:
  - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
  - --collector.filesystem.fs-types-exclude=^(rootfs|autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$

alertmanager:
  enabled: false
grafana:
  enabled: false
defaultRules:
  create: false

kubeScheduler:
  serviceMonitor:
    # TODO fix this:
    insecureSkipVerify: true

kubeControllerManager:
  serviceMonitor:
    # TODO fix this:
    insecureSkipVerify: true
