apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client
spec:
  commonName: query-observer.dnation.cloud
  dnsNames:
  - query-observer.dnation.cloud
  issuerRef:
    kind: Issuer
    name: issuer-ca
  secretName: query-observer.dnation.cloud
  usages:
  - client auth
