{
 "title": "OpenStack overview",
 "description": "OpenStack dashboard using the Prometheus OpenStack exporter (https://github.com/openstack-exporter/openstack-exporter)",
 "tags": [ "openstack" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(openstack_identity_up,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(openstack_identity_up,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Keystone status",
   "type": "stat",
   "description": "Reports the status of the Keystone service",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_identity_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nova status",
   "type": "stat",
   "description": "Reports the status of the Nova service",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Neutron status",
   "type": "stat",
   "description": "Reports the status of the Neutron service",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_neutron_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cinder status",
   "type": "stat",
   "description": "Reports the status of the Cinder service",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "openstack_cinder_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Glance status",
   "type": "stat",
   "description": "Reports the status of the Glance service",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "openstack_glance_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Placement status",
   "type": "stat",
   "description": "Reports the status of the Placement service",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_placement_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ironic status",
   "type": "stat",
   "description": "Reports the status of the Ironic service",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "openstack_ironic_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Designate status",
   "type": "stat",
   "description": "Reports the status of the Designate service",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "openstack_designate_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loadbalancer status",
   "type": "stat",
   "description": "Reports the status of the Loadbalancer service",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_loadbalancer_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Object store status",
   "type": "stat",
   "description": "Reports the status of the Object store service",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_object_store_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container infrastructure status",
   "type": "stat",
   "description": "Reports the status of the Container infrastructure service",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "openstack_container_infra_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heat status",
   "type": "stat",
   "description": "Reports the status of the Heat service",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_heat_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gnocchi status",
   "type": "stat",
   "description": "Reports the status of the Gnocchi service",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_gnocchi_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trove status",
   "type": "stat",
   "description": "Reports the status of the Trove service",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_trove_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Overall CPU cores usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (openstack_placement_resource_usage{job=~\"$job\", instance=~\"$instance\", resourcetype=\"VCPU\"})",
     "legendFormat": "{{instance}}-used-vcpu-cores"
    },
    {
     "expr": "sum by (instance) (openstack_placement_resource_total{job=~\"$job\", instance=~\"$instance\", resourcetype=\"VCPU\"})",
     "legendFormat": "{{instance}}-total-vcpu-cores"
    }
   ]
  },
  {
   "title": "Overall memory usage (TiB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (openstack_placement_resource_usage{job=~\"$job\",instance=~\"$instance\", resourcetype=\"MEMORY_MB\"}) / 1024 / 1024",
     "legendFormat": "{{instance}}-memory-in-use"
    },
    {
     "expr": "sum by (instance) (openstack_placement_resource_total{job=~\"$job\",instance=~\"$instance\", resourcetype=\"MEMORY_MB\"}) / 1024 / 1024",
     "legendFormat": "{{instance}}-memory-available"
    }
   ]
  },
  {
   "title": "Local Storage (TB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (openstack_placement_resource_usage{job=~\"$job\",instance=~\"$instance\", resourcetype=\"DISK_GB\"})/1024",
     "legendFormat": "{{instance}}-local-storage-used"
    },
    {
     "expr": "sum by (instance) (openstack_placement_resource_total{job=~\"$job\",instance=~\"$instance\", resourcetype=\"DISK_GB\"})/1024",
     "legendFormat": "{{instance}}-local-storage-available"
    }
   ]
  },
  {
   "title": "Keystone",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Keystone status",
     "type": "stat",
     "description": "Reports the status of the Keystone service",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openstack_identity_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Projects",
     "type": "timeseries",
     "description": "The number of projects for the OpenStack cloud",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 29 },
     "targets": [
      {
       "expr": "openstack_identity_projects{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-projects"
      }
     ]
    },
    {
     "title": "Groups",
     "type": "stat",
     "description": "The number of groups for the OpenStack cloud",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openstack_identity_groups{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)"
      }
     ]
    },
    {
     "title": "Domains",
     "type": "stat",
     "description": "The number of domains for the OpenStack cloud",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openstack_identity_domains{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)"
      }
     ]
    },
    {
     "title": "Users",
     "type": "timeseries",
     "description": "The number of users for the OpenStack cloud",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 37 },
     "targets": [
      {
       "expr": "openstack_identity_users{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-users"
      }
     ]
    },
    {
     "title": "Regions",
     "type": "stat",
     "description": "The number of regions for the OpenStack cloud",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openstack_identity_regions{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)"
      }
     ]
    },
    {
     "title": "Project details",
     "type": "table",
     "description": "Details for the projects in the OpenStack cloud.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "openstack_identity_project_info{job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nova",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nova status",
     "type": "stat",
     "description": "Reports the status of the Nova service",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openstack_nova_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "VMs",
     "type": "timeseries",
     "description": "The current number of total and running virtual machines",
     "gridPos": { "h": 8, "w": 10, "x": 3, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "openstack_nova_total_vms{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-VMs"
      }
     ]
    },
    {
     "title": "VCPU usage",
     "type": "timeseries",
     "description": "Percentage of the maximum number of virtual CPUs in use for each project",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "openstack_nova_limits_vcpus_used{job=~\"$job\",instance=~\"$instance\"} / clamp_min(openstack_nova_limits_vcpus_max{job=~\"$job\",instance=~\"$instance\"}, 1)",
       "legendFormat": "{{instance}}-{{tenant}}"
      }
     ]
    },
    {
     "title": "Nova agents up",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_nova_agent_state{job=~\"$job\",instance=~\"$instance\", adminState=\"enabled\"}) OR on() vector(-1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Nova agents down",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(openstack_nova_agent_state{job=~\"$job\",instance=~\"$instance\", adminState=\"enabled\"})-sum(openstack_nova_agent_state{job=~\"$job\",instance=~\"$instance\", adminState=\"enabled\"}) OR on() vector(-1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "description": "Percentage of the maximum amount of memory in use for each project",
     "gridPos": { "h": 8, "w": 10, "x": 3, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "openstack_nova_limits_memory_used{job=~\"$job\",instance=~\"$instance\"} / clamp_min(openstack_nova_limits_memory_max{job=~\"$job\",instance=~\"$instance\"}, 1)",
       "legendFormat": "{{instance}}-{{tenant}}"
      }
     ]
    },
    {
     "title": "Instance usage",
     "type": "timeseries",
     "description": "Percentage of the maximum number of instances in use for each project",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "openstack_nova_limits_instances_used{job=~\"$job\",instance=~\"$instance\"} / clamp_min(openstack_nova_limits_instances_max{job=~\"$job\",instance=~\"$instance\"}, 1)",
       "legendFormat": "{{instance}}-{{tenant}}"
      }
     ]
    },
    {
     "title": "Agents status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "openstack_nova_agent_state{job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Neutron",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Neutron status",
     "type": "stat",
     "description": "Reports the status of the Neutron service",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openstack_neutron_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Networks",
     "type": "timeseries",
     "description": "The number of networks managed by Neutron",
     "gridPos": { "h": 8, "w": 10, "x": 3, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "openstack_neutron_networks{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-networks"
      }
     ]
    },
    {
     "title": "Subnets",
     "type": "timeseries",
     "description": "The number of subnets managed by Neutron",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "openstack_neutron_subnets{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-subnets"
      }
     ]
    },
    {
     "title": "Neutron agents up",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_neutron_agent_state{job=~\"$job\",instance=~\"$instance\", adminState=\"up\"}) OR on() vector(-1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Neutron agents down",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(openstack_neutron_agent_state{job=~\"$job\",instance=~\"$instance\", adminState=\"up\"})-sum(openstack_neutron_agent_state{job=~\"$job\",instance=~\"$instance\", adminState=\"up\"}) OR on() vector(-1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Routers",
     "type": "timeseries",
     "description": "The number of routers managed by Neutron",
     "gridPos": { "h": 8, "w": 10, "x": 3, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "openstack_neutron_routers{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-routers-total"
      },
      {
       "expr": "openstack_neutron_routers_not_active{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-routers-inactive"
      }
     ]
    },
    {
     "title": "Ports",
     "type": "timeseries",
     "description": "The number of ports managed by Neutron",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (instance) (openstack_neutron_port{job=~\"$job\",instance=~\"$instance\"}) ",
       "legendFormat": "{{instance}}-ports-total"
      },
      {
       "expr": "count by (instance)(openstack_neutron_port{status!=\"ACTIVE\", job=~\"$job\",instance=~\"$instance\"})",
       "legendFormat": "{{instance}}-ports-inactive"
      },
      {
       "expr": "openstack_neutron_ports_no_ips{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-ports-no-IPs"
      }
     ]
    },
    {
     "title": "Floating IPs",
     "type": "timeseries",
     "description": "The number of public IP addresses managed by Neutron",
     "gridPos": { "h": 8, "w": 10, "x": 3, "y": 47 },
     "targets": [
      {
       "expr": "openstack_neutron_floating_ips{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-IP-total"
      },
      {
       "expr": "openstack_neutron_floating_ips_associated_not_active{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-IPs-associated-inactive"
      }
     ]
    },
    {
     "title": "IPs used by subnets",
     "type": "timeseries",
     "description": "The usage of available IP addresses broken down by subnets",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job, instance, ip_version, subnet_name) (openstack_neutron_network_ip_availabilities_used{job=~\"$job\",instance=~\"$instance\"}) / sum by (job, instance, ip_version, subnet_name)(openstack_neutron_network_ip_availabilities_total{job=~\"$job\",instance=~\"$instance\"})",
       "legendFormat": "{{instance}}-{{subnet_name}}"
      }
     ]
    },
    {
     "title": "Security groups",
     "type": "timeseries",
     "description": "The number of Security groups managed by Neutron",
     "gridPos": { "h": 8, "w": 10, "x": 3, "y": 55 },
     "targets": [
      {
       "expr": "openstack_neutron_security_groups{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-sec-groups"
      }
     ]
    },
    {
     "title": "Router details",
     "type": "table",
     "description": "Detailed view of the routers managed by Neutron",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "openstack_neutron_router{job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Port details",
     "type": "table",
     "description": "Detailed view of the ports managed by Neutron",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "openstack_neutron_port{job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Agents status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "openstack_neutron_agent_state{job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cinder",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cinder status",
     "type": "stat",
     "description": "Reports the status of the Cinder service",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "openstack_cinder_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Volumes",
     "type": "timeseries",
     "description": "The number of volumes managed by Cinder",
     "gridPos": { "h": 8, "w": 10, "x": 3, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "openstack_cinder_volumes{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-volumes"
      }
     ]
    },
    {
     "title": "Volume status",
     "type": "timeseries",
     "description": "The current status of volumes in Cinder",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "openstack_cinder_volume_status_counter{job=~\"$job\",instance=~\"$instance\", status=~\"error|error_backing-up|error_deleting|error_extending|error_restoring\"} > 0",
       "legendFormat": "{{instance}}-{{status}}"
      },
      {
       "expr": "openstack_cinder_volume_status_counter{job=~\"$job\",instance=~\"$instance\", status!~\"error|error_backing-up|error_deleting|error_extending|error_restoring\"} > 0",
       "legendFormat": "{{instance}}-{{status}}"
      }
     ]
    },
    {
     "title": "Cinder agents up",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(openstack_cinder_agent_state{job=~\"$job\",instance=~\"$instance\", adminState=\"enabled\"}) OR on() vector(-1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cinder agents down",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(openstack_cinder_agent_state{job=~\"$job\",instance=~\"$instance\", adminState=\"enabled\"})-sum(openstack_cinder_agent_state{job=~\"$job\",instance=~\"$instance\", adminState=\"enabled\"}) OR on() vector(-1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Volume usage",
     "type": "timeseries",
     "description": "The percent of volume storage in use for Cinder.",
     "gridPos": { "h": 8, "w": 10, "x": 3, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "openstack_cinder_limits_volume_used_gb{job=~\"$job\",instance=~\"$instance\"} / clamp_min(openstack_cinder_limits_volume_max_gb{job=~\"$job\",instance=~\"$instance\"}, 1)",
       "legendFormat": "{{instance}}-{{tenant}}"
      }
     ]
    },
    {
     "title": "Backup usage",
     "type": "timeseries",
     "description": "The percent of backup storage in use for Cinder.",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "openstack_cinder_limits_backup_used_gb{job=~\"$job\",instance=~\"$instance\"} / clamp_min(openstack_cinder_limits_backup_max_gb{job=~\"$job\",instance=~\"$instance\"}, 1)",
       "legendFormat": "{{instance}}-{{tenant}}"
      }
     ]
    },
    {
     "title": "Pool usage",
     "type": "timeseries",
     "description": "The percent of pool capacity in use for Cinder",
     "gridPos": { "h": 8, "w": 10, "x": 3, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(openstack_cinder_pool_capacity_total_gb{job=~\"$job\",instance=~\"$instance\"} - openstack_cinder_pool_capacity_free_gb{job=~\"$job\",instance=~\"$instance\"}) / clamp_min(openstack_cinder_pool_capacity_total_gb{job=~\"$job\",instance=~\"$instance\"}, 1)",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    },
    {
     "title": "Snapshots",
     "type": "timeseries",
     "description": "The number of volume snapshots in Cinder",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "openstack_cinder_snapshots{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-snapshots"
      }
     ]
    },
    {
     "title": "Agents status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "openstack_cinder_agent_state{job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Glance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Glance status",
     "type": "stat",
     "description": "Reports the status of the Glance service",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "openstack_glance_up{job=~\"$job\",instance=~\"$instance\"} OR on() vector(-1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Image count",
     "type": "timeseries",
     "description": "The number of images present in Glance",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 33 },
     "targets": [
      {
       "expr": "openstack_glance_images{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-images"
      }
     ]
    },
    {
     "title": "Images",
     "type": "table",
     "description": "Details for the images in Glance.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "openstack_glance_image_bytes{job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}