{
 "title": "Database",
 "description": "Basic Mysql dashboard for the prometheus exporter ",
 "tags": [
  "Databases",
  "backgroundservices",
  "testbed-dashboard"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "release", "query": "label_values(mysql_up,release)" }
  ]
 },
 "panels": [
  {
   "title": "Global status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Galera status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_galera_status_info", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(mysql_global_status_uptime{release=\"$release\"})"
    }
   ]
  },
  {
   "title": "Mysql Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{release=\"$release\"}",
     "legendFormat": "current {{ instance }}"
    },
    {
     "expr": "min(mysql_global_variables_max_connections{release=\"$release\"})",
     "legendFormat": "Max allowed"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "mysql  disk reads vs writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_innodb_data_reads{release=\"$release\"}[10m])",
     "legendFormat": "reads {{ instance }}"
    },
    {
     "expr": "irate(mysql_global_status_innodb_data_written{release=\"$release\"}[10m])",
     "legendFormat": "write  {{ instance }}"
    },
    { "legendFormat": "write  {{ instance }}" }
   ]
  },
  {
   "title": "mysql network received vs sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_bytes_received{release=\"$release\"}[5m])",
     "legendFormat": "received {{ instance }}"
    },
    {
     "expr": "irate(mysql_global_status_bytes_sent{release=\"$release\"}[5m])",
     "legendFormat": "sent  {{ instance }}"
    }
   ]
  },
  {
   "title": "Query rates",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mysql_global_status_commands_total{release=\"$release\"}[5m])) by (command)",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  {
   "title": "Running Threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_threads_running{release=\"$release\"} ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Aborted clients",
   "type": "graph",
   "description": "The number of connections that were aborted because the client died without closing the connection properly. See Section B.5.2.10, “Communication Errors and Aborted Connections”.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_aborted_clients{release=\"$release\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "mysql aborted Connects",
   "type": "graph",
   "description": "The number of failed attempts to connect to the MySQL server. See Section B.5.2.10, “Communication Errors and Aborted Connections”.\n\nFor additional connection-related information, check the Connection_errors_xxx status variables and the host_cache table.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_aborted_connects{release=\"$release\"}[10m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  }
 ]
}