apiVersion: v1
kind: Service
metadata:
  name: graphite-udp
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: graphite
    app.kubernetes.io/name: graphite
  ports:
  - port: 8125
    targetPort: 8125
    protocol: UDP
