{
 "title": "Zuul Status",
 "tags": [
  "zuul",
  "status",
  "statsd"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Pipelines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Compliance check",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.zuul.tenant.SCS.pipeline.compliance_check.current_changes"
    }
   ]
  },
  {
   "title": "Periodic hourly",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.zuul.tenant.SCS.pipeline.periodic-hourly.current_changes"
    }
   ]
  },
  {
   "title": "Periodic daily",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "stats.gauges.zuul.tenant.SCS.pipeline.periodic-daily.current_changes"
    }
   ]
  },
  {
   "title": " KaaS v1 e2e test",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.zuul.tenant.SCS.pipeline.e2e-test.current_changes"
    }
   ]
  },
  {
   "title": "KaaS v1 e2e quick test",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.zuul.tenant.SCS.pipeline.e2e-quick-test.current_changes"
    }
   ]
  },
  {
   "title": "Check",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.zuul.tenant.SCS.pipeline.check.current_changes"
    }
   ]
  },
  {
   "title": "Post",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "stats.gauges.zuul.tenant.SCS.pipeline.post.current_changes"
    }
   ]
  },
  {
   "title": "Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Zuul Jobs Launched (per Hour)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "target": "alias(summarize(sumSeries(stats_counts.zuul.tenant.SCS.pipeline.*.all_jobs), '1h'), 'All Jobs')"
    }
   ]
  },
  {
   "title": "Node Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(stats.gauges.zuul.nodepool.current_requests, 'Requests')"
    }
   ]
  },
  {
   "title": "GitHub Events (per Hour)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(summarize(stats_counts.zuul.event.github.check_run, '1h'), 'Check run')"
    },
    {
     "target": "alias(summarize(stats_counts.zuul.event.github.pull_request, '1h'), 'Pull request')"
    },
    {
     "target": "alias(summarize(stats_counts.zuul.event.github.pull_request_review, '1h'), 'Pull request review')"
    },
    {
     "target": "alias(summarize(stats_counts.zuul.event.github.push, '1h'), 'Push')"
    }
   ]
  },
  {
   "title": "Test Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(stats.gauges.nodepool.nodes.building, 'Building')"
    },
    {
     "target": "alias(stats.gauges.nodepool.nodes.ready, 'Available')"
    },
    {
     "target": "alias(stats.gauges.nodepool.nodes.in-use, 'In Use')"
    },
    {
     "target": "alias(stats.gauges.nodepool.nodes.used, 'Used')"
    },
    {
     "target": "alias(stats.gauges.nodepool.nodes.deleting, 'Deleting')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.nodepool.provider.*.max_servers), 'Max')"
    }
   ]
  },
  {
   "title": "Executors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Executors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(stats.gauges.zuul.executors.online, 'Online')"
    },
    {
     "target": "alias(stats.gauges.zuul.executors.accepting, 'Accepting')"
    }
   ]
  },
  {
   "title": "Running Builds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasSub(stats.gauges.zuul.executor.*.running_builds, '.*\\.(.*).*', '\\1')"
    }
   ]
  },
  {
   "title": "Executor Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(stats.gauges.zuul.executors.jobs_queued, 'Queued Jobs')"
    },
    {
     "target": "alias(stats.gauges.zuul.executors.jobs_running, 'Running Jobs')"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasSub(scale(stats.gauges.zuul.executor.*.load_average, 0.01), '.*\\.(.*).*', '\\1')"
    }
   ]
  },
  {
   "title": "Starting Builds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasSub(stats.gauges.zuul.executor.*.starting_builds, '.*\\.(.*).*', '\\1')"
    }
   ]
  },
  {
   "title": "Used HDD (Percentage)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasSub(scale(stats.gauges.zuul.executor.*.pct_used_hdd, 0.01), '.*\\.(.*).*', '\\1')"
    }
   ]
  },
  {
   "title": "Used RAM (Percentage)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasSub(scale(stats.gauges.zuul.executor.*.pct_used_ram, 0.01), '.*\\.(.*).*', '\\1')"
    }
   ]
  },
  {
   "title": "Mergers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mergers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(stats.gauges.zuul.mergers.online, 'Online')"
    }
   ]
  },
  {
   "title": "Merger Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(stats.gauges.zuul.mergers.jobs_queued, 'Queued Jobs')"
    },
    {
     "target": "alias(stats.gauges.zuul.mergers.jobs_running, 'Running Jobs')"
    }
   ]
  },
  {
   "title": "Web",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Streams",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasSub(stats.gauges.zuul.web.server.*.streamers, '.*\\.(.*).*', '\\1')"
    }
   ]
  },
  {
   "title": "Threadpool Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(stats.gauges.zuul.web.server.*.threadpool.queue, '.*\\.(.*).*', '\\1')"
    }
   ]
  },
  {
   "title": "Threadpool Idle",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(stats.gauges.zuul.web.server.*.threadpool.idle, '.*\\.(.*).*', '\\1')"
    }
   ]
  },
  {
   "title": "ZooKeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Zuul Event Processing Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "ms", "label": "time" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(stats.timers.zuul.tenant.*.event_enqueue_processing_time.mean), 'Trigger Events')"
    }
   ]
  }
 ]
}