{
 "title": "Zuul Nodepool",
 "tags": [
  "zuul",
  "nodepool",
  "statsd"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Building",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(stats.gauges.nodepool.provider.*.nodes.building)"
    }
   ]
  },
  {
   "title": "Ready",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(stats.gauges.nodepool.provider.*.nodes.ready)"
    }
   ]
  },
  {
   "title": "In Use",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(stats.gauges.nodepool.provider.*.nodes.in-use)"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(stats.gauges.nodepool.provider.*.nodes.used)"
    }
   ]
  },
  {
   "title": "Deleting",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(stats.gauges.nodepool.provider.*.nodes.deleting)"
    }
   ]
  },
  {
   "title": "Hold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(stats.gauges.nodepool.provider.*.nodes.hold)"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(stats.gauges.nodepool.provider.*.nodes.failed)"
    }
   ]
  },
  {
   "title": "Nodepool Images",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Building Nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.nodepool.label.*.nodes.building, 4)"
    }
   ]
  },
  {
   "title": "Ready Nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.nodepool.label.*.nodes.ready, 4)"
    }
   ]
  },
  {
   "title": "In-use Nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.nodepool.label.*.nodes.in-use, 4)"
    }
   ]
  },
  {
   "title": "Deleting Nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.nodepool.label.*.nodes.deleting, 4)"
    }
   ]
  },
  {
   "title": "Node Launches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ready Node Launch Attempts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(summarize(stats_counts.nodepool.launch.provider.*.ready, '1m'), 4)"
    }
   ]
  },
  {
   "title": "Error Node Launch Attempts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(smartSummarize(sumSeries(stats_counts.nodepool.launch.provider.*.error.*), '1m'), 4)"
    }
   ]
  },
  {
   "title": "Time to Ready",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(stats.timers.nodepool.launch.provider.*.ready.mean, 5)"
    }
   ]
  }
 ]
}