clusterMonitoring:
  clusters:
  - name: Observer
    label: observer-cluster
    description: 'Observer cluster monitoring'
  - name: Harbor
    description: 'Harbor cluster monitoring'
    label: harbor-cluster
    apps:
    - name: harbor
      description: Harbor
      jobName: harbor
      templates:
        harbor:
          enabled: true
